Name        : maui-settings
Version     : 0.3.1
Release     : 1
Group       : System/Base
License     : MIT
Summary     : Customizations for Maui
Description : |
  Customizations for Maui.
URL         : http://www.maui-project.org/
NoFiles     : True

Macros:
    - plymouth_theme;solar

Configure: none
Builder: none

SubPackages:
    - Name: system
      Summary: Maui default system configuration
      Group: System/Base
      Description: |
        This package configures several aspects of the system to
        implement better defaults for Maui.
      Files:
          - "%config %{_sysconfdir}/sysctl.d/10-console-messages.conf"
          - "%{_sysconfdir}/udev/rules.d/10-disk-scheduler.rules"
    - Name: plymouth
      Summary: Maui default configuration for Plymouth
      Group: System/Base
      Description: |
        This package contains installs and configures the Maui
        theme for Plymouth.
      Requires:
          - plymouth-theme-%{plymouth_theme}
      Files:
          - "%config %{_datadir}/plymouth/plymouthd.defaults"
