# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-settings

# >> macros
# << macros
%define plymouth_theme solar

Summary:    Customizations for Maui
Version:    0.2.0
Release:    1
Group:      System/Base
License:    MIT
URL:        http://www.maui-project.org/
Source100:  maui-settings.yaml

%description
Customizations for Maui.


%package system
Summary:    Maui default system configuration
Group:      System/Base

%description system
This package configures several aspects of the system to
implement better defaults for Maui.


%package plymouth
Summary:    Maui default configuration for Plymouth
Group:      System/Base
Requires:   plymouth-theme-%{plymouth_theme}

%description plymouth
This package contains installs and configures the Maui
theme for Plymouth.


%prep
# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# Create default configuration for Plymouth
mkdir -p %{buildroot}%{_datadir}/plymouth
cat > %{buildroot}%{_datadir}/plymouth/plymouthd.defaults <<EOF
# Distribution defaults. Changes to this file will get overwritten during
# upgrades.
[Daemon]
Theme=%{plymouth_theme}
EOF

# Avoid Plymouth being interrupted by kernel messages
mkdir -p %{buildroot}%{_sysconfdir}/sysctl.d
cat > %{buildroot}%{_sysconfdir}/sysctl.d/10-console-messages.conf <<EOF
# The following stops low-level messages on console
kernel.printk = 4 5 1 7
EOF
# << install pre

# >> install post
# << install post


%files system
%defattr(-,root,root,-)
%config %{_sysconfdir}/sysctl.d/10-console-messages.conf
# >> files system
# << files system

%files plymouth
%defattr(-,root,root,-)
%config %{_datadir}/plymouth/plymouthd.defaults
# >> files plymouth
# << files plymouth
