# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-settings

# >> macros
# << macros
%define plymouth_theme solar

Summary:    Customizations for Maui
Version:    0.1.0
Release:    1
Group:      System/Base
License:    MIT
URL:        http://www.maui-project.org/
Source100:  maui-settings.yaml

%description
Customizations for Maui.


%package plymouth
Summary:    Maui default configuration for Plymouth
Group:      System/Base
Requires:   plymouth-theme-%{plymouth_theme}

%description plymouth
This package contains installs and configures the Maui
theme for Plymouth.


%prep
# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}
# << install pre

# >> install post
# << install post

%post plymouth
# >> post plymouth
plymouth-set-default-theme %{plymouth_theme}
# << post plymouth

%postun plymouth
# >> postun plymouth
plymouth-set-default-theme --reset
# << postun plymouth


%files plymouth
%defattr(-,root,root,-)
# >> files plymouth
# << files plymouth
