Name        : maui-settings
Version     : 37
Release     : 1
Group       : System/Base
License     : MIT
Summary     : Customizations for Maui
Description : |
  Customizations for Maui.
URL         : http://www.maui-project.org/
NoFiles     : True
BuildArch   : noarch
SetupOptions: -q -n %{name}-%{version}

Macros:
    - theme;wind

PkgConfigBR:
    - systemd

Configure: none
Builder: none

SubPackages:
    - Name: system
      Summary: Maui default system configuration
      Group: System/Base
      Description: |
        This package configures several aspects of the system to
        implement better defaults for Maui.
      Files:
          - "%{_sysctldir}/10-console-messages.conf"
          - "%{_udevrulesdir}/10-disk-scheduler.rules"
    - Name: plymouth
      Summary: Maui default configuration for Plymouth
      Group: System/Base
      Description: |
        This package contains installs and configures the Maui
        theme for Plymouth.
      Provides:
          - plymouth-system-theme
      Conflicts:
          - plymouth-system-theme
      Requires:
          - plymouth
          - plymouth-plugin-two-step
          - plymouth-theme-%{theme}
      Files:
          - "%{_datadir}/plymouth/plymouthd.defaults"
    - Name: plasma5
      Summary: Maui default configuration for Plasma 5
      Group: System/Base
      Description: |
        This package implements Maui defaults for Plasma 5.
      Requires:
          - kf5-filesystem
          - "%{theme}-icon-theme"
          - "%{theme}-cursor-theme"
          - "%{theme}-plasma-theme"
          - "%{theme}-wallpapers"
          - noto-sans-fonts
      Files:
          - "%config %{_sysconfdir}/xdg/kdeglobals"
          - "%config %{_sysconfdir}/xdg/kcminputrc"
          - "%config %{_sysconfdir}/xdg/powerdevilrc"
          - "%config %{_sysconfdir}/xdg/powerdevilprofilesrc"
