# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       maui-settings

# >> macros
# << macros
%define theme wind

Summary:    Customizations for Maui
Version:    38
Release:    1
Group:      System/Base
License:    MIT
BuildArch:  noarch
URL:        http://www.maui-project.org/
Source0:    %{name}-%{version}.tar.xz
Source100:  maui-settings.yaml
BuildRequires:  pkgconfig(systemd)

%description
Customizations for Maui.


%package system
Summary:    Maui default system configuration
Group:      System/Base

%description system
This package configures several aspects of the system to
implement better defaults for Maui.


%package plymouth
Summary:    Maui default configuration for Plymouth
Group:      System/Base
Requires:   plymouth
Requires:   plymouth-plugin-two-step
Requires:   plymouth-theme-%{theme}
Provides:   plymouth-system-theme
Conflicts:  plymouth-system-theme

%description plymouth
This package contains installs and configures the Maui
theme for Plymouth.


%package plasma5
Summary:    Maui default configuration for Plasma 5
Group:      System/Base
Requires:   kf5-filesystem
Requires:   %{theme}-icon-theme
Requires:   %{theme}-cursor-theme
Requires:   %{theme}-plasma-theme
Requires:   %{theme}-wallpapers
Requires:   noto-sans-fonts

%description plasma5
This package implements Maui defaults for Plasma 5.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# Create default configuration for Plymouth
install -D -m 644 plymouth/plymouthd.defaults %{buildroot}%{_datadir}/plymouth/plymouthd.defaults
sed -i 's,@THEME@,%{theme},g' %{buildroot}%{_datadir}/plymouth/plymouthd.defaults

# Avoid Plymouth being interrupted by kernel messages
install -D -m 644 sysctl/console-messages.conf %{buildroot}%{_sysctldir}/10-console-messages.conf

# Configure disk schedulers
install -D -m 644 udev/disk-scheduler.rules %{buildroot}%{_udevrulesdir}/10-disk-scheduler.rules

#
# Plasma 5 configuration
#
mkdir -p %{buildroot}%{_sysconfdir}/xdg

# kdeglobals
install -D -m 644 kde/kdeglobals %{buildroot}%{_sysconfdir}/xdg/kdeglobals
sed -i 's,@THEME@,%{theme},g' %{buildroot}%{_sysconfdir}/xdg/kdeglobals

# kcminput
install -D -m 644 kde/kcminputrc %{buildroot}%{_sysconfdir}/xdg/kcminputrc
sed -i 's,@THEME@,%{theme},g' %{buildroot}%{_sysconfdir}/xdg/kcminputrc

# powerdevil
install -D -m 644 powerdevil/powerdevilrc %{buildroot}%{_sysconfdir}/xdg/powerdevilrc
install -D -m 644 powerdevil/powerdevilprofilesrc %{buildroot}%{_sysconfdir}/xdg/powerdevilprofilesrc
# << install pre

# >> install post
# << install post


%files system
%defattr(-,root,root,-)
%{_sysctldir}/10-console-messages.conf
%{_udevrulesdir}/10-disk-scheduler.rules
# >> files system
# << files system

%files plymouth
%defattr(-,root,root,-)
%{_datadir}/plymouth/plymouthd.defaults
# >> files plymouth
# << files plymouth

%files plasma5
%defattr(-,root,root,-)
%config %{_sysconfdir}/xdg/kdeglobals
%config %{_sysconfdir}/xdg/kcminputrc
%config %{_sysconfdir}/xdg/powerdevilrc
%config %{_sysconfdir}/xdg/powerdevilprofilesrc
# >> files plasma5
# << files plasma5
